# Generated by Django 3.1 on 2020-08-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeRegion', models.CharField(max_length=200)),
                ('storeName', models.CharField(max_length=200)),
                ('storeFloor', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
    ]
