# Generated by Django 3.1 on 2020-08-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='storeImg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
